name: Create Branch on Issue

on:
  issues:
    types: [opened]

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Create branch for issue
      uses: peter-evans/create-or-update-comment@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        issue-number: ${{ github.event.issue.number }}
        body: |
          Branch for this issue created: `issue-${{ github.event.issue.number }}-${{ github.event.issue.title }}`
        
    - name: Create branch
      run: |
        echo "Creating branch for issue #${{ github.event.issue.number }}"
        git checkout -b "issue-${{ github.event.issue.number }}-${{ github.event.issue.title }}"
        git push origin "issue-${{ github.event.issue.number }}-${{ github.event.issue.title }}"
